from __future__ import annotations

from pathlib import Path

# Scripts live in code/; every path below is anchored to the repository root so
# a script can be run from anywhere (`python code/phylogenetic_signal.py` or
# `cd code && python phylogenetic_signal.py` both work).
PACKAGE_ROOT = Path(__file__).resolve().parents[1]
FROZEN_ROOT = PACKAGE_ROOT

LAYER_FILES = {
    "CCAM": "Changes in color of aerial mycelium (CCAM).xlsx",
    "CCVM": "Changes in color of vegetative mycelium (CCVM).xlsx",
    "CMP": "Changes in mycelium production (CMP).xlsx",
    "CS": "Changes in sporulation (CS).xlsx",
    "IG": "Inhibition of growth (IG).xlsx",
    "IC": "Invasion of colony (IC).xlsx",
    "RP": "Release of a pigment (RP).xlsx",
    "IRP": "Inhibition of release of pigment (IRP).xlsx",
    "IAC_RAC": "Induction of antimicrobial compounds of the other (IAC) release of antibacterial compounds (RAC).xlsx",
    "IAC_RDE": "Induction of antimicrobial compounds of the other (IAC) release of degrading enzyme (RDE).xlsx",
    "IRAC": "Inhibition of release of antimicrobial compounds (IRAC).xlsx",
    "RAC": "Release of antimicrobial compounds (RAC).xlsx",
}


ANNOTATION_DIR = PACKAGE_ROOT / 'data' / 'annotation'
PHYLOGENY_DIR = PACKAGE_ROOT / 'data' / 'phylogeny'

# Strain-level annotation shipped with the bundle. See data/annotation/DATA_NOTES.md
# for the join to the interaction matrices and the open data-integrity items.
ANNOTATION_FILES = {
    'sequences_16S': ANNOTATION_DIR / '16S_strepto_R',
    'distance_matrix': ANNOTATION_DIR / 'distance_matrix.xlsx',
    'carbohydrate_profile': ANNOTATION_DIR / 'atb_profile.xlsx',
}

# Derived by code/prep_phylogeny.py and code/build_tree.py.
PHYLOGENY_FILES = {
    'clean_fasta': PHYLOGENY_DIR / '16S_clean.fasta',
    'label_map': PHYLOGENY_DIR / 'label_map.csv',
    'tree': PHYLOGENY_DIR / 'tree.nwk',
}


def find_layer_file(filename: str) -> Path:
    path = PACKAGE_ROOT / 'data' / 'matrices_xls' / filename
    if path.exists():
        return path
    raise FileNotFoundError(filename)


def find_annotation_file(key: str) -> Path:
    path = ANNOTATION_FILES[key]
    if path.exists():
        return path
    raise FileNotFoundError(path)


RESULTS_DIR = PACKAGE_ROOT / 'results'
CACHE_DIR = PACKAGE_ROOT / '.cache'

# Intermediate per-strain tables. Regenerated by the pipeline, but committed
# because several scripts consume them directly.
DATA_DIR_ROOT = PACKAGE_ROOT / 'data'
EMBEDDING_CSV = DATA_DIR_ROOT / 'ecological_embeddings_4D.csv'
IDENTITY_CSV = DATA_DIR_ROOT / 'ecological_identity_with_PCs_and_clusters.csv'
