#!/usr/bin/env python3
"""Final Tables 1 and 2, as Markdown (for Word) and CSV (for the record).

Table 1 differs from the pre_final version in one substantive way: it now carries
a null-model column for *every* structural statistic the Results discuss, not just
the SCC. Reciprocity and transitivity previously had no null anywhere in the
codebase, so the manuscript's claims about them ("IG z approaching 6", "transitivity
reduced in six layers") are taken from reciprocity_transitivity.py.

Sources, all regenerated by run_all.py:
    layer_descriptors.csv          density, R_p, mutual pairs, mean out-degree
    connectivity.csv                       largest SCC + null
    reciprocity_transitivity.csv reciprocity + transitivity nulls
    tableS2_layer_overlap_full.csv                   layer overlap vs null
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
TABLES = REPO / "results" / "tables"
OUT = Path(__file__).resolve().parents[1] / "results" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

CATEGORY = {"IG": "DA", "IC": "DA", "RAC": "DA", "IAC_RAC": "IA", "IAC_RDE": "IA", "IRAC": "IA",
            "RP": "MM", "IRP": "MM", "CCAM": "MC", "CCVM": "MC", "CMP": "MC", "CS": "MC"}
CAT_ORDER = ["DA", "IA", "MM", "MC"]

# Mechanistic readings carried over from the pre_final Table 2; the numbers beside
# them are recomputed, the wording is the authors'.
INTERPRETATION = {
    ("CCAM", "CCVM"): "Coupled aerial/vegetative pigmentation; scored from the same colonies, so reported separately",
    ("CCAM", "CMP"): "Aerial-mycelium colour with mycelial production; shared assay context precludes attributing this to one pathway",
    ("CCVM", "CMP"): "Vegetative pigmentation co-varies with mycelial production",
    ("CMP", "CS"): "Mycelium production and sporulation: joint output of the developmental cascade",
    ("CCVM", "CS"): "Pigment biosynthesis tied to the developmental transition into aerial growth",
    ("CCAM", "CS"): "Aerial pigmentation and sporulation, both downstream of the same developmental switch",
    ("IRAC", "RAC"): "Inhibition and release act on the same antimicrobial axis",
    ("IG", "IRAC"): "Growth inhibition with suppression of antimicrobial release; biological coupling and shared assay covariance are not separable here",
    ("CS", "RAC"): "Sporulation response co-occurs with antimicrobial release, consistent with competition sensing",
    ("IAC_RAC", "RAC"): "Induced and constitutive release avoid the same dyads: a strain needing induction is typically not also a constitutive producer toward that target",
}


def fmt(x: float, nd: int = 3) -> str:
    return "—" if x is None or (isinstance(x, float) and not np.isfinite(x)) else f"{x:.{nd}f}"


def z_str(z: float, sig: bool) -> str:
    if z is None or not np.isfinite(z):
        return "—"
    return f"{z:+.2f}" + ("*" if sig else "")


def sci(q: float) -> str:
    if q >= 0.01:
        return f"{q:.3f}"
    exp = int(np.floor(np.log10(q)))
    return f"{q / 10**exp:.1f}×10^{exp}^"


def to_md(df: pd.DataFrame) -> str:
    header = "| " + " | ".join(df.columns) + " |"
    sep = "| " + " | ".join(["---"] * len(df.columns)) + " |"
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([header, sep, *rows])


def qcol(p14, layer, stat):
    """Empirical BY q for one statistic, or an em-dash for a degenerate null."""
    col = f"{stat}_q_by"
    if col not in p14.columns:
        return "—"
    v = p14.loc[layer, col]
    return sci(v) if np.isfinite(v) else "—"


def table1() -> str:
    p7 = pd.read_csv(TABLES / "layer_descriptors.csv").set_index("layer")
    p5 = pd.read_csv(TABLES / "connectivity_null.csv").set_index("layer")
    p14 = pd.read_csv(TABLES / "reciprocity_transitivity.csv").set_index("layer")

    rows = []
    for cat in CAT_ORDER:
        layers = [l for l in CATEGORY if CATEGORY[l] == cat]
        layers.sort(key=lambda l: -p7.loc[l, "edge_density"])
        for l in layers:
            rows.append({
                "Category": cat,
                "Layer": l,
                "Edges E": int(round(p7.loc[l, "edge_density"] * 60 * 59)),
                "Density ρ": fmt(p7.loc[l, "edge_density"]),
                "R_p": fmt(p7.loc[l, "reciprocity_pairs"]),
                "z (R_p)": z_str(p14.loc[l, "reciprocity_z"], bool(p14.loc[l, "reciprocity_significant_by"])),
                "q (R_p)": qcol(p14, l, "reciprocity"),
                "Mean out-deg": fmt(p7.loc[l, "mean_out_degree"], 2),
                "Mutual pairs": int(p7.loc[l, "mutual_pairs"]),
                "Largest SCC": int(p5.loc[l, "scc_obs"]),
                "z (SCC)": z_str(p5.loc[l, "z"], bool(p5.loc[l, "significant_by"])),
                "q (SCC)": sci(p5.loc[l, "p_fdr_by"]) if np.isfinite(p5.loc[l, "p_fdr_by"]) else "—",
                "Transitivity_und": fmt(p14.loc[l, "transitivity_obs"]),
                "z (T)": z_str(p14.loc[l, "transitivity_z"], bool(p14.loc[l, "transitivity_significant_by"])),
                "q (T)": qcol(p14, l, "transitivity"),
            })
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "table1_layer_architecture.csv", index=False)

    n_draws = int(p5["n_null_draws"].iloc[0])
    cat_means = {c: np.mean([p7.loc[l, "mean_out_degree"] for l in CATEGORY if CATEGORY[l] == c]) for c in CAT_ORDER}
    caption = (
        f"**Table 1. Per-layer architecture of the twelve interaction networks.** "
        f"N = 60 strains, binary directed projection A_l = 1[M_l > 0]. "
        f"Density ρ = E / N(N−1); R_p = mutual / connected dyads; SCC = size of the largest strongly connected "
        f"component; transitivity = closed triplets / all triplets on the undirected projection. "
        f"Each z compares the observed value with {n_draws:,} degree-preserving directed edge-swap rewirings "
        f"of that layer; q is the Benjamini-Yekutieli-corrected empirical probability within that "
        f"statistic's family of twelve, and * marks q < 0.05. Transitivity is computed on the "
        f"undirected projection of each layer. "
        f"An em-dash marks a degenerate null (the statistic is identically zero, or one, in every draw). "
        f"Layers are grouped by functional category (DA = direct antagonism, IA = induced antagonism, "
        f"MM = metabolic modulation, MC = morphogenetic control) and ordered within each by density. "
        f"Category means of mean out-degree: "
        + ", ".join(f"{c} = {cat_means[c]:.1f}" for c in CAT_ORDER) + "."
    )
    return caption + "\n\n" + to_md(df) + "\n"


def table2() -> str:
    p4 = pd.read_csv(TABLES / "tableS2_layer_overlap_full.csv")
    sig = p4[p4["significant_by"]].copy().sort_values("z", ascending=False)
    rows = []
    for r in sig.itertuples():
        key = (r.layer1, r.layer2) if (r.layer1, r.layer2) in INTERPRETATION else (r.layer2, r.layer1)
        rows.append({
            "Pair": f"{r.layer1}–{r.layer2}" + (" †" if r.methodological_confound else ""),
            "Categories": f"{CATEGORY[r.layer1]}–{CATEGORY[r.layer2]}",
            "J_obs": fmt(r.J_obs),
            "J_null mean": fmt(r.J_null_mean),
            "z": f"{r.z:+.2f}",
            "BY q": sci(r.p_fdr_by),
            "Direction": "over" if r.z > 0 else "under",
            "Phenotypic interpretation": INTERPRETATION.get(key, ""),
        })
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "table2_layer_overlap.csv", index=False)

    n_draws = int(p4["n_null_draws"].iloc[0])
    n_bio_over = int(((sig["z"] > 0) & (~sig["methodological_confound"])).sum())
    n_bio_under = int(((sig["z"] < 0) & (~sig["methodological_confound"])).sum())
    caption = (
        f"**Table 2. Layer pairs departing from a degree-preserving null.** "
        f"Jaccard similarity of directed edge sets compared with {n_draws:,} independent degree-preserving "
        f"edge-swap rewirings of each layer; z = (J_obs − mean J_null) / sd(J_null). Two-sided empirical p with "
        f"the Phipson–Smyth (M+1)/(N+1) correction, then Benjamini–Yekutieli across all {len(p4)} pairs "
        f"(BY rather than BH because each layer appears in eleven tests). Only pairs with q < 0.05 are shown. "
        f"Of the {len(p4) - 1} biologically interpretable pairs, {n_bio_over} show enriched and {n_bio_under} "
        f"depleted overlap. † CCAM–CCVM was designated a priori as a shared-measurement confound: both colours "
        f"were scored from the same colonies at the same time, so it is corrected within the family but "
        f"excluded from biological interpretation. Enriched pairs fall into two groupings — the "
        f"morphogenetic-developmental programme (six MC×MC pairs plus the CS–RAC bridge) and two actions on the "
        f"same antimicrobial axis (IRAC–RAC, IG–IRAC)."
    )
    return caption + "\n\n" + to_md(df) + "\n"


def main() -> None:
    t1, t2 = table1(), table2()
    print("wrote table1_layer_architecture.csv and table2_layer_overlap.csv")
    print("\n" + t1 + "\n" + t2)


if __name__ == "__main__":
    main()
